id: P003278
initial_creation_type: ocr
source_metadata:
  id: bdr:W19973
  title: བྱང་བདག་རྣམ་རྒྱལ་གྲགས་བཟང་གི་རྣམ་ཐར
  author: ''
  volumes:
    6540ff423c3447bca6d039f7be0791ab:
      image_group_id: I3864
      title: ''
      volume_number: 1
      total_pages: 136
