id: P003278
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:52:10.873025
source_metadata:
  id: bdr:W19973
  title: བྱང་བདག་རྣམ་རྒྱལ་གྲགས་བཟང་གི་རྣམ་ཐར
  author: ''
  volumes:
    6540ff423c3447bca6d039f7be0791ab:
      image_group_id: I3864
      title: ''
      volume_number: 1
      total_pages: 136
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
